language: "ar"

pipeline:
- name: SpacyNLP
  model: "xx_ent_wiki_sm"     # يدعم العربية والإنجليزية
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  random_seed: 42
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.4           # إذا كانت الثقة أقل من 40%، استخدم fallback
  ambiguity_threshold: 0.1    # يمنع اختيار intent متردد فيه

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20250617-060618-tough-operator
