services:
  - type: web
    name: haram-chatbot
    env: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
